<!-- Page d'accueil -->
<h2><i class="fa fa-cubes" ></i> Exercice base de donnée et son blog</h2>

Configurer un template de blog et reliez le à sa base de donnée puis apportez y votre touche personnelle (css/bootstrap).

Pour cela :
<ul>
    <li>téléchargez le fichier Zip </li>
    <li>configurez sa base de donnée (Phpmyadmin)</li>    
    <li>Etablissez le lien entre le blog et sa base de donnée.</li>
    <li>débugué les erreurs</li>    
</ul>

<p>Have fun !</p>


